# preload = ~/Pictures/Wallpapers/wallpaper-desktop
# wallpaper = eDP-1,~/Pictures/Wallpapers/wallpaper-desktop
# 显示器留空则表示为所有显示器设置
# hyprpaper 暂不支持符号链接硬编码壁纸热加载
# wallpaper = ,~/Pictures/Wallpapers/wallpaper-desktop