# 设置最大伽马值
max-gamma = 150
# 日间模式
profile {
	time = 6:00
	identify = true
	gamma = 1.0
}
# 夜间模式
profile {
	time = 18:00
	temperature = 4500
	gamma = 0.8
}
# 深夜模式
profile {
	time = 22:00
	temperature = 3500
	gamma = 0.6
}