general {
	lock_cmd = pidof hyprlock || hyprlock
	ignore_dbus_inhibit = false
}

# 锁屏
listener {
	timeout = 300
	on-timeout = loginctl lock-session
	on-resume = notify-send "Welcome Back!"
}

# 无操作时每隔7分钟自动随机切换壁纸
listener {
	timeout = 520
	on-timeout = sys-wallpaper
}

# 熄屏
listener {
 	timeout = 600
	on-timeout = hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
}

# 挂起
listener {
	timeout = 900
	on-timeout = systemctl suspend
}